trigger:
- master
- development

pr:
- development

variables:
  BuildConfiguration: 'Release'
  BackendSolution: 'backend/IDE.sln'
  TestProjects: 'backend/**/*[Tt]ests/*.csproj'

jobs:
- job: 'Frontend'
  pool:
    vmImage: 'ubuntu-16.04'
    demands: npm
  steps:
  - template: ci-templates/build-frontend.yml

- job: 'Backend'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: ci-templates/build-backend.yml
