version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: 'elasticsearch'
    environment:
      discovery.type: single-node
    expose:
      - '9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0    
    container_name: 'kibana'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
