// <auto-generated />
using System;
using IDE.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDE.DAL.Migrations
{
    [DbContext(typeof(IdeContext))]
    [Migration("20190809143837_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IDE.DAL.Entities.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BuildFinished");

                    b.Property<string>("BuildMessage");

                    b.Property<DateTime>("BuildStarted");

                    b.Property<int>("BuildStatus");

                    b.Property<int>("ProjectId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 604, DateTimeKind.Local).AddTicks(6592),
                            BuildMessage = "Quo ut architecto molestias non ut consequatur ad occaecati quod.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 605, DateTimeKind.Local).AddTicks(5383),
                            BuildStatus = 0,
                            ProjectId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(116),
                            BuildMessage = "Odit iusto sapiente corrupti voluptatem laboriosam alias modi sunt labore.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(347),
                            BuildStatus = 1,
                            ProjectId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(717),
                            BuildMessage = "Et quos qui atque nemo repellat consequatur qui sit sint.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(820),
                            BuildStatus = 0,
                            ProjectId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(856),
                            BuildMessage = "Cupiditate atque aut sequi neque eaque illo est numquam aut.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(902),
                            BuildStatus = 0,
                            ProjectId = 18,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(923),
                            BuildMessage = "Sed magnam et dolorum repellat sed veniam non dolorem ipsam.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(959),
                            BuildStatus = 1,
                            ProjectId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1000),
                            BuildMessage = "Perferendis modi ullam dicta et et velit qui vel sint.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1041),
                            BuildStatus = 0,
                            ProjectId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1061),
                            BuildMessage = "Et ipsum doloribus pariatur est sint dolorum molestiae debitis facere.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1133),
                            BuildStatus = 0,
                            ProjectId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1159),
                            BuildMessage = "Omnis consequatur beatae ex dolorem molestiae sed minus voluptatem eum.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1195),
                            BuildStatus = 0,
                            ProjectId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1216),
                            BuildMessage = "Error nam labore nemo id asperiores nobis molestiae aperiam aut.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1252),
                            BuildStatus = 1,
                            ProjectId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1277),
                            BuildMessage = "Doloremque esse molestias dolores rem vel est ea officiis consectetur.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1313),
                            BuildStatus = 0,
                            ProjectId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1334),
                            BuildMessage = "Illum illum nisi voluptatum laboriosam soluta est aut hic tenetur.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1447),
                            BuildStatus = 1,
                            ProjectId = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1473),
                            BuildMessage = "Quos quo deserunt quod eveniet dolores eaque ut in nihil.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1514),
                            BuildStatus = 0,
                            ProjectId = 18,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1534),
                            BuildMessage = "Quos iusto deleniti est voluptatum quia pariatur iure dolor et.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1570),
                            BuildStatus = 1,
                            ProjectId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1591),
                            BuildMessage = "Quaerat deserunt qui beatae praesentium illum similique qui quia aut.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1627),
                            BuildStatus = 1,
                            ProjectId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1647),
                            BuildMessage = "Non quam consequatur esse fugit sed officia voluptatibus consectetur quis.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1714),
                            BuildStatus = 0,
                            ProjectId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1740),
                            BuildMessage = "Sint quisquam harum ipsam pariatur aut sit consequuntur debitis dignissimos.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1776),
                            BuildStatus = 1,
                            ProjectId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1797),
                            BuildMessage = "Voluptate voluptatem voluptates ipsum praesentium tempore iste sit et molestiae.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1833),
                            BuildStatus = 1,
                            ProjectId = 16,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1853),
                            BuildMessage = "Totam ut temporibus quasi corporis et illum voluptatibus corporis nulla.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1889),
                            BuildStatus = 1,
                            ProjectId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1910),
                            BuildMessage = "Et hic ipsum illo aut sunt explicabo accusamus impedit ut.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(1940),
                            BuildStatus = 0,
                            ProjectId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2043),
                            BuildMessage = "Et nihil exercitationem enim nostrum ab omnis explicabo perspiciatis numquam.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2156),
                            BuildStatus = 0,
                            ProjectId = 17,
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2233),
                            BuildMessage = "Eius molestias quaerat aut voluptatum dicta nesciunt suscipit officiis id.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2352),
                            BuildStatus = 0,
                            ProjectId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2403),
                            BuildMessage = "Corrupti nam rerum possimus cumque porro ab deleniti pariatur aut.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2460),
                            BuildStatus = 1,
                            ProjectId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2496),
                            BuildMessage = "Assumenda blanditiis aperiam aliquam id fugiat et fugiat officiis qui.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2542),
                            BuildStatus = 1,
                            ProjectId = 13,
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2619),
                            BuildMessage = "Maiores vero quos dolor aut veniam vitae quo error necessitatibus.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2665),
                            BuildStatus = 0,
                            ProjectId = 16,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2701),
                            BuildMessage = "Et possimus nam quis in sunt architecto et voluptatem nihil.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2748),
                            BuildStatus = 0,
                            ProjectId = 13,
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2778),
                            BuildMessage = "Quia rerum fuga laborum beatae minima voluptatem voluptates minus consectetur.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2830),
                            BuildStatus = 1,
                            ProjectId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2866),
                            BuildMessage = "Ea rerum porro sed similique dolorem totam modi eius corrupti.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2917),
                            BuildStatus = 0,
                            ProjectId = 11,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(2948),
                            BuildMessage = "Aperiam provident accusamus nam sequi consectetur dolorem ut aut eos.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3046),
                            BuildStatus = 0,
                            ProjectId = 20,
                            UserId = 3
                        },
                        new
                        {
                            Id = 29,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3087),
                            BuildMessage = "Non quidem id aut similique cum corporis iure ipsum consequuntur.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3138),
                            BuildStatus = 0,
                            ProjectId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3179),
                            BuildMessage = "Voluptatum ratione facilis a praesentium qui aut necessitatibus dolore dolorum.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3231),
                            BuildStatus = 0,
                            ProjectId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3267),
                            BuildMessage = "Quibusdam ut omnis nostrum consequatur quas aliquam possimus saepe fugiat.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3328),
                            BuildStatus = 1,
                            ProjectId = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 32,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3364),
                            BuildMessage = "Quos sed quibusdam eos voluptate nam omnis sit quo sit.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3462),
                            BuildStatus = 1,
                            ProjectId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 33,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3503),
                            BuildMessage = "Omnis voluptas sint nobis perferendis error illum provident aut in.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3555),
                            BuildStatus = 1,
                            ProjectId = 18,
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3591),
                            BuildMessage = "Cumque eos vel culpa enim voluptatem fuga ut sapiente et.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3642),
                            BuildStatus = 0,
                            ProjectId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3683),
                            BuildMessage = "Autem sint sit vitae rerum amet qui magni maxime velit.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3735),
                            BuildStatus = 1,
                            ProjectId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 36,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3771),
                            BuildMessage = "Inventore occaecati eum laborum et amet voluptatibus sunt sapiente est.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3868),
                            BuildStatus = 1,
                            ProjectId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 37,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3909),
                            BuildMessage = "Similique non eos quibusdam recusandae dolorem ullam et amet ullam.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(3997),
                            BuildStatus = 1,
                            ProjectId = 16,
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4069),
                            BuildMessage = "Molestiae id sit a ducimus sed quis dolores sapiente odit.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4182),
                            BuildStatus = 0,
                            ProjectId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4223),
                            BuildMessage = "Voluptates ea quia esse dolorem vel hic dolor et et.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4279),
                            BuildStatus = 1,
                            ProjectId = 19,
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            BuildFinished = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4326),
                            BuildMessage = "Sit voluptates sit officiis eius officiis vel quis possimus et.",
                            BuildStarted = new DateTime(2019, 8, 9, 17, 38, 36, 610, DateTimeKind.Local).AddTicks(4495),
                            BuildStatus = 1,
                            ProjectId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.GitCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<int>("Provider");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("GitCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Soledad_Pfeffer24",
                            PasswordHash = "zgiQ+MpZcpo5TgV/EF8Dd8tu45bvAfIBGs0JHRv9GCg=",
                            PasswordSalt = "UcVFYNQfJRkkuluC4m6+LGPnNMEkJg39Xyy1DPKQba8=",
                            Provider = 2,
                            Url = "http://anne.info"
                        },
                        new
                        {
                            Id = 2,
                            Login = "Maynard.Haley",
                            PasswordHash = "D70nYsNWdA4QaJAKgV7fM2Yv04FAzu6YA/MAWNuTBW4=",
                            PasswordSalt = "U01NvULQdz/hiA5OBRXBnufY0M8SgRZYh8ccWXpIQ+8=",
                            Provider = 2,
                            Url = "http://estelle.net"
                        },
                        new
                        {
                            Id = 3,
                            Login = "Alison_Kovacek",
                            PasswordHash = "0DDmOyOIMgkGvTTJHZ9xta+BDqUpeSo0nn+LnW/HAq4=",
                            PasswordSalt = "tE7ZE2pBffmbiwX96Zs36BjHNdHrGgMbqaRSNbErowg=",
                            Provider = 1,
                            Url = "http://cedrick.org"
                        },
                        new
                        {
                            Id = 4,
                            Login = "Ebba_Ortiz53",
                            PasswordHash = "xf8pZozFzmtrOaDy4+E/Jte+3fFDBVeB0BQwb9XHBXw=",
                            PasswordSalt = "cW7kBeejcWaCzdzbgcwVzi/BTv2F36WS3s9ZQ7a3Grg=",
                            Provider = 0,
                            Url = "http://rick.info"
                        },
                        new
                        {
                            Id = 5,
                            Login = "Cordie2",
                            PasswordHash = "4BfSukoVcpl9Aqc98aDX93YmmJ1ppS3vPheih3VJaGo=",
                            PasswordSalt = "RYSeRH79z4UKPCXmZANXqbxKdGiofqVZyUe17iXHNrA=",
                            Provider = 1,
                            Url = "http://jevon.name"
                        },
                        new
                        {
                            Id = 6,
                            Login = "Carrie.Spinka64",
                            PasswordHash = "dxv7wIMbMNOUrIn5i/uUwk59zL/lGwKnWnEtTcDQJkM=",
                            PasswordSalt = "t9YupSt6ejALt+pbPJ+a8bMFu3nf3709EH9O8j9nzWs=",
                            Provider = 2,
                            Url = "http://mireya.biz"
                        },
                        new
                        {
                            Id = 7,
                            Login = "Arnoldo.Yost",
                            PasswordHash = "exdgShdBlYf+WhMUR6bQ+GVG/xBHHdTukrFSzk5GwJc=",
                            PasswordSalt = "U+XrtnNwSfOoV6/wIecZRSUSnXUDR7uoZ/AOYbHDCBY=",
                            Provider = 2,
                            Url = "https://julie.com"
                        },
                        new
                        {
                            Id = 8,
                            Login = "Aditya_Mueller5",
                            PasswordHash = "Sym6oPAbeZq4WwNRNCEtRvx4PIY37hprDoKBaLT4+6w=",
                            PasswordSalt = "5baTgBdktrOp8n7hz0hooZLgbqTbU7iD3HO29xlojH8=",
                            Provider = 0,
                            Url = "http://loren.name"
                        },
                        new
                        {
                            Id = 9,
                            Login = "Freida_Rogahn",
                            PasswordHash = "q9JuN4RcwkwcII69quk8y8XxWWjn8IwTORmX7Eyg5A4=",
                            PasswordSalt = "AFIic/GKqCn3WZnA/Yx1WdcyrEVeYuyVCRlL8CZFVog=",
                            Provider = 0,
                            Url = "https://shaylee.info"
                        },
                        new
                        {
                            Id = 10,
                            Login = "Patrick_Pouros",
                            PasswordHash = "rWUxcY3qsU30FPLaS1Pib5zFUx8Gr4TNxd9p748nKPA=",
                            PasswordSalt = "Nyn7b+IbU8c7xlGDfhnqb+8OKBhuiNIK19ivgkN8m18=",
                            Provider = 1,
                            Url = "http://dawson.info"
                        },
                        new
                        {
                            Id = 11,
                            Login = "Mohamed34",
                            PasswordHash = "NRxTIealqDiEs2/sLICArOzk7JcVADGXNKBlL05s4RI=",
                            PasswordSalt = "QgOW4SfQ4M8zvWCJGQhN2YLQwjGXy5KAkd+uFLB7TbA=",
                            Provider = 2,
                            Url = "https://jordan.name"
                        },
                        new
                        {
                            Id = 12,
                            Login = "Nyasia_Fadel",
                            PasswordHash = "gkGjQTUQH8ogFNXVTSvW1BjkoTEfmjlTkdBDo8FL1mI=",
                            PasswordSalt = "85SKqk3ZUr/knmaFRqy74fdOY9nwbKdwBw+aPLtjs/E=",
                            Provider = 2,
                            Url = "https://dawn.net"
                        },
                        new
                        {
                            Id = 13,
                            Login = "Jonathan_Cartwright",
                            PasswordHash = "AlRUlZQlw7xbI09IlTo7YukrI9TSS+0w8iUFGO+LYHo=",
                            PasswordSalt = "livk4D56cTBFexxNbJudswStEa1wQyUWKWeVpYLvgTI=",
                            Provider = 2,
                            Url = "https://ethelyn.info"
                        },
                        new
                        {
                            Id = 14,
                            Login = "Briana83",
                            PasswordHash = "BNCLX14i7szfa+XCbJyG99wgwSeG2EiXapdX6PhoGu4=",
                            PasswordSalt = "lLKLIGwwz9D8+0tmOMCpCp2l353G81ZEaUbNJH7Tda0=",
                            Provider = 0,
                            Url = "http://keenan.org"
                        },
                        new
                        {
                            Id = 15,
                            Login = "Zetta28",
                            PasswordHash = "TkAMNOYHVwsakszvFr2xacfUKzofhJM06SANrz0PMDI=",
                            PasswordSalt = "T0t3+VkiruPi4759YyXRwraV3icCT3iaU5mAYz5Lxtw=",
                            Provider = 0,
                            Url = "https://felipe.name"
                        },
                        new
                        {
                            Id = 16,
                            Login = "Nia24",
                            PasswordHash = "ww8rpxzI4Cqhhtzli4lsFbnMMYwLP354/HfgFxPWHeE=",
                            PasswordSalt = "sOmsi1W6KSD9lCkjHOaTuV5ind1agApzY4S4PEh4Gt4=",
                            Provider = 0,
                            Url = "https://rosalia.info"
                        },
                        new
                        {
                            Id = 17,
                            Login = "Leora13",
                            PasswordHash = "Q9F6k0qupSGrabboaCkLpfuZEfyF7f5dCorFa7vn3RM=",
                            PasswordSalt = "kFgO0XZWBDzaBYQx4h3MNPQ6ZjdTPrL9xvExqJQyz4M=",
                            Provider = 1,
                            Url = "http://kaleigh.net"
                        },
                        new
                        {
                            Id = 18,
                            Login = "Luis_Hyatt",
                            PasswordHash = "fPErDRxfJh6qmeswS8wAXIMBjnYxcrKYfXe5h8vhQSY=",
                            PasswordSalt = "Inj12yc8mF+melzlTROxiwzv+mtNwAfh0n/wmDN6d6o=",
                            Provider = 0,
                            Url = "http://estel.com"
                        },
                        new
                        {
                            Id = 19,
                            Login = "Brannon52",
                            PasswordHash = "xHTbp3buUfw7EVPXOFq/Y5ioZy9CcqWynbqn/QgKQ8E=",
                            PasswordSalt = "kuZoQytRoNRtalhf5REsaHiRF0+XMElHMpNX5ZsH8r4=",
                            Provider = 0,
                            Url = "http://roman.info"
                        },
                        new
                        {
                            Id = 20,
                            Login = "Ransom.Nitzsche",
                            PasswordHash = "YBv0ClxhAIbS6LOYUH9QkYqEQXjLIJFNeXZeAzzrQs8=",
                            PasswordSalt = "ADN+6xvgmFYhv61Pa0ROrC59S3zjUusov/PWlFsI+58=",
                            Provider = 2,
                            Url = "https://adrain.net"
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://s3.amazonaws.com/uifaces/faces/twitter/imammuht/128.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://s3.amazonaws.com/uifaces/faces/twitter/normanbox/128.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://s3.amazonaws.com/uifaces/faces/twitter/digitalmaverick/128.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://loremflickr.com/640/480?lock=1480224036"
                        },
                        new
                        {
                            Id = 5,
                            Url = "https://loremflickr.com/640/480?lock=1822844665"
                        },
                        new
                        {
                            Id = 6,
                            Url = "https://loremflickr.com/640/480?lock=647665779"
                        },
                        new
                        {
                            Id = 7,
                            Url = "https://loremflickr.com/640/480?lock=1129885050"
                        },
                        new
                        {
                            Id = 8,
                            Url = "https://loremflickr.com/640/480?lock=1915200731"
                        },
                        new
                        {
                            Id = 9,
                            Url = "https://loremflickr.com/640/480?lock=750228139"
                        },
                        new
                        {
                            Id = 10,
                            Url = "https://loremflickr.com/640/480?lock=1022100058"
                        },
                        new
                        {
                            Id = 11,
                            Url = "https://loremflickr.com/640/480?lock=249167178"
                        },
                        new
                        {
                            Id = 12,
                            Url = "https://loremflickr.com/640/480?lock=795639316"
                        },
                        new
                        {
                            Id = 13,
                            Url = "https://loremflickr.com/640/480?lock=1143379573"
                        },
                        new
                        {
                            Id = 14,
                            Url = "https://loremflickr.com/640/480?lock=2045055810"
                        },
                        new
                        {
                            Id = 15,
                            Url = "https://loremflickr.com/640/480?lock=1126424437"
                        },
                        new
                        {
                            Id = 16,
                            Url = "https://loremflickr.com/640/480?lock=105575879"
                        },
                        new
                        {
                            Id = 17,
                            Url = "https://loremflickr.com/640/480?lock=1627246728"
                        },
                        new
                        {
                            Id = 18,
                            Url = "https://loremflickr.com/640/480?lock=1619135858"
                        },
                        new
                        {
                            Id = 19,
                            Url = "https://loremflickr.com/640/480?lock=251969388"
                        },
                        new
                        {
                            Id = 20,
                            Url = "https://loremflickr.com/640/480?lock=666130004"
                        },
                        new
                        {
                            Id = 21,
                            Url = "https://loremflickr.com/640/480?lock=2009551175"
                        },
                        new
                        {
                            Id = 22,
                            Url = "https://loremflickr.com/640/480?lock=639109103"
                        },
                        new
                        {
                            Id = 23,
                            Url = "https://loremflickr.com/640/480?lock=245164000"
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessModifier");

                    b.Property<int>("AuthorId");

                    b.Property<int>("CompilerType");

                    b.Property<int>("CountOfBuildAttempts");

                    b.Property<int>("CountOfSaveBuilds");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("GitCredentialId");

                    b.Property<int>("Language");

                    b.Property<int?>("LogoId");

                    b.Property<string>("Name");

                    b.Property<string>("ProjectLink");

                    b.Property<int>("ProjectType");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GitCredentialId");

                    b.HasIndex("LogoId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessModifier = 1,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 586, DateTimeKind.Local).AddTicks(1989),
                            Description = "Aperiam non quisquam ipsam sapiente.",
                            GitCredentialId = 11,
                            Language = 1,
                            LogoId = 10,
                            Name = "aut",
                            ProjectLink = "https://linnea.net",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 2,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(4141),
                            Description = "Enim ut tempora ea hic.",
                            GitCredentialId = 17,
                            Language = 1,
                            LogoId = 5,
                            Name = "sit",
                            ProjectLink = "https://pansy.net",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 3,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 9,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(4886),
                            Description = "Animi voluptatem rerum reiciendis minus.",
                            GitCredentialId = 8,
                            Language = 0,
                            LogoId = 23,
                            Name = "itaque",
                            ProjectLink = "http://amely.name",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 4,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 10,
                            CountOfSaveBuilds = 10,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5076),
                            Description = "Eaque cum in voluptates soluta.",
                            GitCredentialId = 18,
                            Language = 0,
                            LogoId = 23,
                            Name = "ut",
                            ProjectLink = "http://kelvin.biz",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 5,
                            AccessModifier = 0,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5174),
                            Description = "Ducimus suscipit laborum at nisi.",
                            GitCredentialId = 20,
                            Language = 1,
                            LogoId = 7,
                            Name = "eaque",
                            ProjectLink = "https://aaliyah.net",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 6,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 9,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5261),
                            Description = "Adipisci est qui assumenda omnis.",
                            GitCredentialId = 16,
                            Language = 1,
                            LogoId = 15,
                            Name = "nihil",
                            ProjectLink = "https://gerhard.name",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 7,
                            AccessModifier = 1,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5390),
                            Description = "Nostrum amet sit et eaque.",
                            GitCredentialId = 11,
                            Language = 1,
                            LogoId = 12,
                            Name = "reiciendis",
                            ProjectLink = "https://christophe.org",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 8,
                            AccessModifier = 0,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5482),
                            Description = "Omnis soluta iste vero sit.",
                            GitCredentialId = 15,
                            Language = 1,
                            LogoId = 7,
                            Name = "assumenda",
                            ProjectLink = "http://juana.info",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 9,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5570),
                            Description = "Deleniti culpa et inventore non.",
                            GitCredentialId = 8,
                            Language = 1,
                            LogoId = 5,
                            Name = "velit",
                            ProjectLink = "http://reuben.org",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 10,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 9,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5657),
                            Description = "Odit et dolorem officia architecto.",
                            GitCredentialId = 18,
                            Language = 1,
                            LogoId = 11,
                            Name = "eveniet",
                            ProjectLink = "https://ressie.biz",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 11,
                            AccessModifier = 0,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 7,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5827),
                            Description = "Rerum dolores placeat sed vitae.",
                            GitCredentialId = 20,
                            Language = 0,
                            LogoId = 4,
                            Name = "ea",
                            ProjectLink = "https://taylor.net",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 12,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 10,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(5935),
                            Description = "Accusantium necessitatibus quas et ullam.",
                            GitCredentialId = 11,
                            Language = 0,
                            LogoId = 7,
                            Name = "incidunt",
                            ProjectLink = "http://ahmed.net",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 13,
                            AccessModifier = 1,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6022),
                            Description = "Voluptas et ut sed aliquam.",
                            GitCredentialId = 1,
                            Language = 0,
                            LogoId = 23,
                            Name = "deleniti",
                            ProjectLink = "http://ozella.com",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 14,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 10,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6161),
                            Description = "Voluptatibus dicta adipisci numquam maxime.",
                            GitCredentialId = 19,
                            Language = 1,
                            LogoId = 7,
                            Name = "accusantium",
                            ProjectLink = "https://rodrigo.biz",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 15,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 9,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6248),
                            Description = "Et dolorem quidem rem corporis.",
                            GitCredentialId = 7,
                            Language = 0,
                            LogoId = 10,
                            Name = "iure",
                            ProjectLink = "http://wilson.info",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 16,
                            AccessModifier = 1,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6336),
                            Description = "Dicta unde nesciunt iusto totam.",
                            GitCredentialId = 2,
                            Language = 0,
                            LogoId = 20,
                            Name = "quia",
                            ProjectLink = "http://breanne.com",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 17,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6459),
                            Description = "Corrupti molestias dolor at neque.",
                            GitCredentialId = 9,
                            Language = 1,
                            LogoId = 16,
                            Name = "numquam",
                            ProjectLink = "https://katheryn.org",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 18,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 9,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6547),
                            Description = "Perspiciatis sit ex culpa laudantium.",
                            GitCredentialId = 10,
                            Language = 0,
                            LogoId = 20,
                            Name = "amet",
                            ProjectLink = "http://ebba.net",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 19,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6634),
                            Description = "Excepturi ut iure minus voluptates.",
                            GitCredentialId = 17,
                            Language = 1,
                            LogoId = 13,
                            Name = "voluptatem",
                            ProjectLink = "http://mossie.net",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 20,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 17, 38, 36, 594, DateTimeKind.Local).AddTicks(6752),
                            Description = "Tempore et quae quis quidem.",
                            GitCredentialId = 7,
                            Language = 0,
                            LogoId = 7,
                            Name = "aliquid",
                            ProjectLink = "https://jada.biz",
                            ProjectType = 1
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.Property<int>("UserAccess");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = 3,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 13,
                            UserId = 2,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 9,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 18,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 10,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 7,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 4,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 11,
                            UserId = 2,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 2,
                            UserId = 3,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 11,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 12,
                            UserId = 1,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 20,
                            UserId = 1,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = 2,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 3,
                            UserId = 1,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 20,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 6,
                            UserId = 2,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 15,
                            UserId = 2,
                            UserAccess = 2
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IDE.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("GitHubUrl");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("LastName");

                    b.Property<string>("NickName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<DateTime>("RegisteredAt");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 2,
                            Birthday = new DateTime(2012, 3, 18, 3, 46, 49, 194, DateTimeKind.Local).AddTicks(7887),
                            Email = "Berniece90@yahoo.com",
                            FirstName = "Hassan",
                            GitHubUrl = "https://luisa.biz",
                            LastActive = new DateTime(2019, 8, 9, 17, 38, 36, 339, DateTimeKind.Local).AddTicks(1141),
                            LastName = "Runolfsdottir",
                            NickName = "Nichole.Aufderhar35",
                            PasswordHash = "ixLMaVg872GUeDwhSKb0C2554ghwbVKLb7McwV4di8s=",
                            PasswordSalt = "k/QVpbeac6UgC6088iO6pJWuoGrhgHz8uYqKJGP3dsg=",
                            RegisteredAt = new DateTime(2019, 8, 9, 17, 38, 36, 338, DateTimeKind.Local).AddTicks(9568)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 2,
                            Birthday = new DateTime(2010, 3, 28, 18, 35, 20, 298, DateTimeKind.Local).AddTicks(1904),
                            Email = "Rachelle.Bernier@gmail.com",
                            FirstName = "Princess",
                            GitHubUrl = "http://keshaun.org",
                            LastActive = new DateTime(2019, 8, 9, 17, 38, 36, 411, DateTimeKind.Local).AddTicks(2527),
                            LastName = "Goodwin",
                            NickName = "Ericka_Bruen",
                            PasswordHash = "DlvBFwsO4v3Nk8mXhWOPN7moHfwsIO+8d/WmoQ4GQZY=",
                            PasswordSalt = "i+FQKNE6aN9PozlAJ47CkdIr21piqOnPibq7xBrsQ4s=",
                            RegisteredAt = new DateTime(2019, 8, 9, 17, 38, 36, 411, DateTimeKind.Local).AddTicks(2511)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 1,
                            Birthday = new DateTime(2005, 8, 9, 17, 38, 36, 425, DateTimeKind.Local).AddTicks(2510),
                            Email = "test@gmail.com",
                            FirstName = "testUser",
                            LastActive = new DateTime(2019, 8, 9, 17, 38, 36, 425, DateTimeKind.Local).AddTicks(2541),
                            LastName = "testUser",
                            PasswordHash = "4WeLPDrDhomjXFSH/cnp839qu5HKfW1LDvCss5oBttQ=",
                            PasswordSalt = "7585mBdsT9MzwnDQajiKzUiPGMwWDqhHGulF+KtPjuo=",
                            RegisteredAt = new DateTime(2019, 8, 9, 17, 38, 36, 425, DateTimeKind.Local).AddTicks(2546)
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Build", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Project", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany("Builds")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.Project", b =>
                {
                    b.HasOne("IDE.DAL.Entities.User", "Author")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.GitCredential", "GitCredential")
                        .WithMany()
                        .HasForeignKey("GitCredentialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.Image", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.ProjectMember", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IDE.DAL.Entities.User", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
