// <auto-generated />
using System;
using IDE.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDE.DAL.Migrations
{
    [DbContext(typeof(IdeContext))]
    [Migration("20190809115233_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IDE.DAL.Entities.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BuildFinished");

                    b.Property<string>("BuildMessage");

                    b.Property<DateTime>("BuildStarted");

                    b.Property<int>("BuildStatus");

                    b.Property<int>("ProjectId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Builds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 710, DateTimeKind.Local).AddTicks(3937),
                            BuildMessage = "Sed possimus exercitationem magnam tempore et quae quis quidem quia.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 711, DateTimeKind.Local).AddTicks(1448),
                            BuildStatus = 0,
                            ProjectId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(5845),
                            BuildMessage = "Provident praesentium aliquam laudantium quo ut architecto molestias non ut.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(5953),
                            BuildStatus = 1,
                            ProjectId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6205),
                            BuildMessage = "Quod aut incidunt accusantium odit iusto sapiente corrupti voluptatem laboriosam.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6256),
                            BuildStatus = 0,
                            ProjectId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6292),
                            BuildMessage = "Labore sed tempora mollitia et quos qui atque nemo repellat.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6333),
                            BuildStatus = 0,
                            ProjectId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6354),
                            BuildMessage = "Sint enim quis consequatur cupiditate atque aut sequi neque eaque.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6431),
                            BuildStatus = 0,
                            ProjectId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6451),
                            BuildMessage = "Aut numquam et vel sed magnam et dolorum repellat sed.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6493),
                            BuildStatus = 0,
                            ProjectId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6513),
                            BuildMessage = "Ipsam perspiciatis aperiam et perferendis modi ullam dicta et et.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6554),
                            BuildStatus = 0,
                            ProjectId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6575),
                            BuildMessage = "Sint dolore itaque architecto et ipsum doloribus pariatur est sint.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6611),
                            BuildStatus = 1,
                            ProjectId = 19,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6631),
                            BuildMessage = "Facere atque in sint omnis consequatur beatae ex dolorem molestiae.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6693),
                            BuildStatus = 0,
                            ProjectId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6714),
                            BuildMessage = "Eum nemo consequuntur rerum error nam labore nemo id asperiores.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6750),
                            BuildStatus = 1,
                            ProjectId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6770),
                            BuildMessage = "Aut earum voluptatem et doloremque esse molestias dolores rem vel.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6806),
                            BuildStatus = 1,
                            ProjectId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6827),
                            BuildMessage = "Consectetur et praesentium ut illum illum nisi voluptatum laboriosam soluta.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6863),
                            BuildStatus = 1,
                            ProjectId = 17,
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6883),
                            BuildMessage = "Tenetur est similique sit quos quo deserunt quod eveniet dolores.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6914),
                            BuildStatus = 0,
                            ProjectId = 11,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(6971),
                            BuildMessage = "Nihil tempora necessitatibus ea quos iusto deleniti est voluptatum quia.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7016),
                            BuildStatus = 1,
                            ProjectId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7037),
                            BuildMessage = "Et qui natus assumenda quaerat deserunt qui beatae praesentium illum.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7073),
                            BuildStatus = 1,
                            ProjectId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7088),
                            BuildMessage = "Aut consequatur dolores exercitationem non quam consequatur esse fugit sed.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7124),
                            BuildStatus = 1,
                            ProjectId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7145),
                            BuildMessage = "Quis quia voluptatem voluptatum sint quisquam harum ipsam pariatur aut.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7176),
                            BuildStatus = 0,
                            ProjectId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7222),
                            BuildMessage = "Dignissimos porro quia et voluptate voluptatem voluptates ipsum praesentium tempore.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7258),
                            BuildStatus = 1,
                            ProjectId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7278),
                            BuildMessage = "Molestiae culpa omnis facere totam ut temporibus quasi corporis et.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7314),
                            BuildStatus = 1,
                            ProjectId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7335),
                            BuildMessage = "Nulla qui aut consequuntur et hic ipsum illo aut sunt.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7366),
                            BuildStatus = 0,
                            ProjectId = 18,
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7386),
                            BuildMessage = "Ut architecto sit dolorem et nihil exercitationem enim nostrum ab.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7422),
                            BuildStatus = 1,
                            ProjectId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7443),
                            BuildMessage = "Numquam suscipit consequatur qui eius molestias quaerat aut voluptatum dicta.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7505),
                            BuildStatus = 0,
                            ProjectId = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7525),
                            BuildMessage = "Id aut consectetur blanditiis corrupti nam rerum possimus cumque porro.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7556),
                            BuildStatus = 0,
                            ProjectId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7577),
                            BuildMessage = "Aut nobis doloremque omnis assumenda blanditiis aperiam aliquam id fugiat.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7607),
                            BuildStatus = 0,
                            ProjectId = 17,
                            UserId = 3
                        },
                        new
                        {
                            Id = 25,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7628),
                            BuildMessage = "Qui est id autem maiores vero quos dolor aut veniam.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7659),
                            BuildStatus = 0,
                            ProjectId = 17,
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7679),
                            BuildMessage = "Necessitatibus quia repellendus excepturi et possimus nam quis in sunt.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7746),
                            BuildStatus = 0,
                            ProjectId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7767),
                            BuildMessage = "Nihil corporis et accusamus quia rerum fuga laborum beatae minima.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7798),
                            BuildStatus = 0,
                            ProjectId = 19,
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7818),
                            BuildMessage = "Consectetur maiores et aut ea rerum porro sed similique dolorem.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7849),
                            BuildStatus = 0,
                            ProjectId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7870),
                            BuildMessage = "Corrupti ipsum quas amet aperiam provident accusamus nam sequi consectetur.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7900),
                            BuildStatus = 0,
                            ProjectId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7921),
                            BuildMessage = "Eos numquam hic consequatur non quidem id aut similique cum.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(7983),
                            BuildStatus = 0,
                            ProjectId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8008),
                            BuildMessage = "Consequuntur quia fugit eos voluptatum ratione facilis a praesentium qui.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8044),
                            BuildStatus = 0,
                            ProjectId = 18,
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8060),
                            BuildMessage = "Dolorum eaque et aperiam quibusdam ut omnis nostrum consequatur quas.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8091),
                            BuildStatus = 0,
                            ProjectId = 16,
                            UserId = 3
                        },
                        new
                        {
                            Id = 33,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8111),
                            BuildMessage = "Fugiat dolorum suscipit sint quos sed quibusdam eos voluptate nam.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8142),
                            BuildStatus = 1,
                            ProjectId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 34,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8173),
                            BuildMessage = "Sit officia voluptatem cum omnis voluptas sint nobis perferendis error.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8265),
                            BuildStatus = 1,
                            ProjectId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 35,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8286),
                            BuildMessage = "In laborum debitis ipsam cumque eos vel culpa enim voluptatem.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8317),
                            BuildStatus = 1,
                            ProjectId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 36,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8337),
                            BuildMessage = "Et explicabo eum numquam autem sint sit vitae rerum amet.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8373),
                            BuildStatus = 0,
                            ProjectId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 37,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8389),
                            BuildMessage = "Velit voluptas non illum inventore occaecati eum laborum et amet.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8420),
                            BuildStatus = 1,
                            ProjectId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 38,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8440),
                            BuildMessage = "Est quidem magni nihil similique non eos quibusdam recusandae dolorem.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8502),
                            BuildStatus = 0,
                            ProjectId = 17,
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8528),
                            BuildMessage = "Ullam excepturi et sint molestiae id sit a ducimus sed.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8558),
                            BuildStatus = 0,
                            ProjectId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 40,
                            BuildFinished = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8579),
                            BuildMessage = "Odit sequi aliquid odit voluptates ea quia esse dolorem vel.",
                            BuildStarted = new DateTime(2019, 8, 9, 14, 52, 32, 713, DateTimeKind.Local).AddTicks(8605),
                            BuildStatus = 1,
                            ProjectId = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.GitCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<int>("Provider");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("GitCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Antoinette42",
                            PasswordHash = "FoLx0E2SvyMtkI2gtR4wkII+O890SFvqBOWEn/Zvqeo=",
                            PasswordSalt = "1LBNk2cV7bgeTDj4e3ZuOgNcwv1HZape9UfT/6Y4X3E=",
                            Provider = 0,
                            Url = "http://armando.net"
                        },
                        new
                        {
                            Id = 2,
                            Login = "Maribel.Bergstrom2",
                            PasswordHash = "nf5Qj4c8DBil/cT/jqIfmG7FMGM+LlmAtdw62jnL0RM=",
                            PasswordSalt = "vMjmerM+M08pU6pPsBr7st4rydqtppY4e5z47936k8Y=",
                            Provider = 2,
                            Url = "http://cyrus.info"
                        },
                        new
                        {
                            Id = 3,
                            Login = "Ian24",
                            PasswordHash = "X5+ZUMy+m5l1Uzt+M96rIusPwiaCai8MtoVAQts11TY=",
                            PasswordSalt = "PORy8o9V7C/dQnYkTLYeKQXlKnqH1dgC022Rr+Cvkk4=",
                            Provider = 2,
                            Url = "http://maximillia.biz"
                        },
                        new
                        {
                            Id = 4,
                            Login = "Cassie_Kassulke10",
                            PasswordHash = "2PCzoalSUaXCDlF/8k91yf6HPmzKPutYhN05rPotIRw=",
                            PasswordSalt = "H1zX+fI335EvNC2QTZkMNhESyN/TCfCeJA2FKcTjJMY=",
                            Provider = 1,
                            Url = "https://connie.com"
                        },
                        new
                        {
                            Id = 5,
                            Login = "Hester75",
                            PasswordHash = "pZDZiGUVHtVIA8VMcr03Pgp3Zmzhb4MaB/8t5W5zT3k=",
                            PasswordSalt = "sfLAbCCiVRK9pyaD+RMik6PoGEM60ikBgwgX6M7NZZc=",
                            Provider = 0,
                            Url = "http://destini.com"
                        },
                        new
                        {
                            Id = 6,
                            Login = "Zion34",
                            PasswordHash = "pfPMQEJDA9NrxJZTbEiwrZSclC6IT0teWBguA9V6YnY=",
                            PasswordSalt = "B2dy5XIJ2S1JYvu3XwYV5k6LCu2kS2dPMsNMht/B2ko=",
                            Provider = 0,
                            Url = "https://ryan.com"
                        },
                        new
                        {
                            Id = 7,
                            Login = "Koby.Goyette14",
                            PasswordHash = "kB/hEEHlLDYHTekwlVtvDbAAr3eQ1pMAuHxLnZSs5/E=",
                            PasswordSalt = "xRsWBLUdCXD8HLKVAeoWx1mE6N/TaioxK9/Om9VM99I=",
                            Provider = 1,
                            Url = "http://mathew.com"
                        },
                        new
                        {
                            Id = 8,
                            Login = "Adrain.Watsica",
                            PasswordHash = "GhulOqoskaI92DH1RL/xngc2YatNN0aMNPKfsZ3DOi4=",
                            PasswordSalt = "7qinCo0k9A0cFwb11qOGE/JWKm7ouAhqrGL4gVqNYGE=",
                            Provider = 0,
                            Url = "https://madisen.com"
                        },
                        new
                        {
                            Id = 9,
                            Login = "Brandi0",
                            PasswordHash = "Mdn3HNZnznFYgdJo1FSEUKS6JP+05Ez5XFdsFqY+1bY=",
                            PasswordSalt = "vvNMkAMdaYmuPQjiOO8UetSQ28C2cOFW5D/ssu9XCms=",
                            Provider = 2,
                            Url = "https://nathanial.info"
                        },
                        new
                        {
                            Id = 10,
                            Login = "Vince_Schmeler56",
                            PasswordHash = "64jqCP6ahNssExpiBuNk7H52tGnCF0nR5kFzPG3zeVM=",
                            PasswordSalt = "Cz16RCTWcXqLYQEw/hC81qdrn5bZoylPz1LhnITSGbk=",
                            Provider = 1,
                            Url = "http://sim.info"
                        },
                        new
                        {
                            Id = 11,
                            Login = "Samara23",
                            PasswordHash = "sUOTHytLYxiKTZAJndKzeLV4OyRSetTW/PAdKc5QoWA=",
                            PasswordSalt = "hiJautuGx0P9Xb80WqPLrUpiE75Sy+8XtjomKm0avR8=",
                            Provider = 2,
                            Url = "https://lamont.net"
                        },
                        new
                        {
                            Id = 12,
                            Login = "Jada97",
                            PasswordHash = "eRTfvuDcft+sKKLtVMYWGG4m4TqvKJ8y8qSPFLOM8Ik=",
                            PasswordSalt = "/2q135IVYT4BxBSQtbztgTIpwMtNZku/aNgG+bHuuLk=",
                            Provider = 0,
                            Url = "https://jannie.biz"
                        },
                        new
                        {
                            Id = 13,
                            Login = "Cassie34",
                            PasswordHash = "7mgmOiiBj5T6w0UYC0A2BGQHesog5hqPIRrOp1Hhxvc=",
                            PasswordSalt = "2uSWR9FTZN9Vbzh3VU7HLuIZzwMx2DhQ8wt6L/C0DH0=",
                            Provider = 1,
                            Url = "https://schuyler.org"
                        },
                        new
                        {
                            Id = 14,
                            Login = "Willis_Romaguera",
                            PasswordHash = "QqVHC8ru00/ayUoq7WdHjo4kH7GNZ7zZiRZFAdl/O+Y=",
                            PasswordSalt = "hg23yenvU+76koD8/vmln0fyf7pBIrnI1XNFRVoWq/A=",
                            Provider = 0,
                            Url = "https://bobbie.info"
                        },
                        new
                        {
                            Id = 15,
                            Login = "Aylin61",
                            PasswordHash = "cCk6yaJa7YB3IDgnjgeBjjUmZk9FATUuGgM1zcfVHw8=",
                            PasswordSalt = "YKKfpBjlzAMzvsTA5EIckGBuQ0ps6Wt+VulDPdFZNZQ=",
                            Provider = 0,
                            Url = "https://briana.com"
                        },
                        new
                        {
                            Id = 16,
                            Login = "Edna.Hahn77",
                            PasswordHash = "Rb2wkBHTugDVYj1c0sERs7V6y896twJTK0kvAYZXM3M=",
                            PasswordSalt = "QsKmmqV0MTCjn4k7JI1uNhmKBY/rpovUes9JpfG95Wo=",
                            Provider = 0,
                            Url = "https://ashlynn.biz"
                        },
                        new
                        {
                            Id = 17,
                            Login = "Titus91",
                            PasswordHash = "af/daPvGEKmnAiYkVbqf2g9vrs5UcerPSStWgx4O8yU=",
                            PasswordSalt = "ovuNc9in5GgWby4Eml6rZCuTbHhQZCpzKr+8HaEZAMI=",
                            Provider = 0,
                            Url = "http://dwight.org"
                        },
                        new
                        {
                            Id = 18,
                            Login = "Kassandra_Kemmer",
                            PasswordHash = "eNFc8H7NdqBo//xXn47WsnD71kJ43aYPQOg7EddM1so=",
                            PasswordSalt = "o1d2kIffwwax196atvFbr3iNvGz/32PeFm7x9RxmsHI=",
                            Provider = 1,
                            Url = "http://destiny.com"
                        },
                        new
                        {
                            Id = 19,
                            Login = "Leann_Jerde71",
                            PasswordHash = "0kkgeL6bCkZWVuy+ZHCK2gG+xSnSf9Tigh1o6Ykn/OE=",
                            PasswordSalt = "N/+FZ0+b/u0XWBfl+kQU2c6d0z5AVvRZ+7wr32WgR5w=",
                            Provider = 0,
                            Url = "http://scot.com"
                        },
                        new
                        {
                            Id = 20,
                            Login = "Rosa_Haley",
                            PasswordHash = "XyIEElbH3HQM6h+04fP3dzPrLqIpcBr79JR97eQvV2w=",
                            PasswordSalt = "S4RD1Y+lNM1WqYPiKAsx89sTef87XVBB7S1lYwzvtjk=",
                            Provider = 0,
                            Url = "https://vivianne.net"
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://picsum.photos/640/480/?image=708"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://picsum.photos/640/480/?image=801"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://picsum.photos/640/480/?image=320"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://picsum.photos/640/480/?image=747"
                        },
                        new
                        {
                            Id = 5,
                            Url = "https://picsum.photos/640/480/?image=920"
                        },
                        new
                        {
                            Id = 6,
                            Url = "https://picsum.photos/640/480/?image=327"
                        },
                        new
                        {
                            Id = 7,
                            Url = "https://picsum.photos/640/480/?image=570"
                        },
                        new
                        {
                            Id = 8,
                            Url = "https://picsum.photos/640/480/?image=967"
                        },
                        new
                        {
                            Id = 9,
                            Url = "https://picsum.photos/640/480/?image=379"
                        },
                        new
                        {
                            Id = 10,
                            Url = "https://picsum.photos/640/480/?image=516"
                        },
                        new
                        {
                            Id = 11,
                            Url = "https://picsum.photos/640/480/?image=125"
                        },
                        new
                        {
                            Id = 12,
                            Url = "https://picsum.photos/640/480/?image=401"
                        },
                        new
                        {
                            Id = 13,
                            Url = "https://picsum.photos/640/480/?image=577"
                        },
                        new
                        {
                            Id = 14,
                            Url = "https://picsum.photos/640/480/?image=1033"
                        },
                        new
                        {
                            Id = 15,
                            Url = "https://picsum.photos/640/480/?image=569"
                        },
                        new
                        {
                            Id = 16,
                            Url = "https://picsum.photos/640/480/?image=53"
                        },
                        new
                        {
                            Id = 17,
                            Url = "https://picsum.photos/640/480/?image=822"
                        },
                        new
                        {
                            Id = 18,
                            Url = "https://picsum.photos/640/480/?image=818"
                        },
                        new
                        {
                            Id = 19,
                            Url = "https://picsum.photos/640/480/?image=127"
                        },
                        new
                        {
                            Id = 20,
                            Url = "https://picsum.photos/640/480/?image=336"
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessModifier");

                    b.Property<int>("AuthorId");

                    b.Property<int>("CompilerType");

                    b.Property<int>("CountOfBuildAttempts");

                    b.Property<int>("CountOfSaveBuilds");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("GitCredentialId");

                    b.Property<int>("Language");

                    b.Property<int?>("LogoId");

                    b.Property<string>("Name");

                    b.Property<string>("ProjectLink");

                    b.Property<int>("ProjectType");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GitCredentialId");

                    b.HasIndex("LogoId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 697, DateTimeKind.Local).AddTicks(7212),
                            Description = "Animi quas animi cumque consequuntur.",
                            GitCredentialId = 17,
                            Language = 1,
                            LogoId = 4,
                            Name = "molestiae",
                            ProjectLink = "http://tia.org",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 2,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(3347),
                            Description = "Non quisquam ipsam sapiente non.",
                            GitCredentialId = 18,
                            Language = 0,
                            LogoId = 3,
                            Name = "voluptas",
                            ProjectLink = "https://mario.org",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 3,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(3850),
                            Description = "Ut tempora ea hic consequatur.",
                            GitCredentialId = 13,
                            Language = 0,
                            LogoId = 7,
                            Name = "rerum",
                            ProjectLink = "https://mattie.biz",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 4,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 9,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(3969),
                            Description = "Voluptatem rerum reiciendis minus quis.",
                            GitCredentialId = 1,
                            Language = 1,
                            LogoId = 19,
                            Name = "deleniti",
                            ProjectLink = "http://kayla.org",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 5,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 10,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4113),
                            Description = "Cum in voluptates soluta officiis.",
                            GitCredentialId = 4,
                            Language = 1,
                            LogoId = 11,
                            Name = "esse",
                            ProjectLink = "https://dejuan.com",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 6,
                            AccessModifier = 0,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 7,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4205),
                            Description = "Suscipit laborum at nisi sapiente.",
                            GitCredentialId = 18,
                            Language = 0,
                            LogoId = 1,
                            Name = "omnis",
                            ProjectLink = "http://nils.biz",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 7,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 9,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4303),
                            Description = "Est qui assumenda omnis facere.",
                            GitCredentialId = 17,
                            Language = 1,
                            LogoId = 9,
                            Name = "est",
                            ProjectLink = "http://lavern.biz",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 8,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 6,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4411),
                            Description = "Amet sit et eaque cupiditate.",
                            GitCredentialId = 17,
                            Language = 0,
                            LogoId = 20,
                            Name = "dolor",
                            ProjectLink = "http://tiana.org",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 9,
                            AccessModifier = 0,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4503),
                            Description = "Soluta iste vero sit maxime.",
                            GitCredentialId = 11,
                            Language = 0,
                            LogoId = 16,
                            Name = "odio",
                            ProjectLink = "https://garrick.org",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 10,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 7,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4591),
                            Description = "Culpa et inventore non ex.",
                            GitCredentialId = 16,
                            Language = 0,
                            LogoId = 9,
                            Name = "dolores",
                            ProjectLink = "https://webster.name",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 11,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4673),
                            Description = "Et dolorem officia architecto at.",
                            GitCredentialId = 16,
                            Language = 0,
                            LogoId = 18,
                            Name = "id",
                            ProjectLink = "https://dusty.info",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 12,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 7,
                            CountOfSaveBuilds = 10,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4832),
                            Description = "Dolores placeat sed vitae delectus.",
                            GitCredentialId = 7,
                            Language = 0,
                            LogoId = 8,
                            Name = "quibusdam",
                            ProjectLink = "https://noe.net",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 13,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 10,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(4915),
                            Description = "Necessitatibus quas et ullam provident.",
                            GitCredentialId = 10,
                            Language = 0,
                            LogoId = 5,
                            Name = "dolores",
                            ProjectLink = "http://marguerite.org",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 14,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 9,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5002),
                            Description = "Et ut sed aliquam aperiam.",
                            GitCredentialId = 10,
                            Language = 1,
                            LogoId = 10,
                            Name = "eos",
                            ProjectLink = "https://breanne.com",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 15,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 10,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5115),
                            Description = "Dicta adipisci numquam maxime repudiandae.",
                            GitCredentialId = 15,
                            Language = 0,
                            LogoId = 1,
                            Name = "nobis",
                            ProjectLink = "https://donato.com",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 16,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 9,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5197),
                            Description = "Dolorem quidem rem corporis laboriosam.",
                            GitCredentialId = 2,
                            Language = 0,
                            LogoId = 8,
                            Name = "aspernatur",
                            ProjectLink = "https://janiya.com",
                            ProjectType = 2
                        },
                        new
                        {
                            Id = 17,
                            AccessModifier = 1,
                            AuthorId = 2,
                            CompilerType = 0,
                            CountOfBuildAttempts = 6,
                            CountOfSaveBuilds = 5,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5285),
                            Description = "Unde nesciunt iusto totam illo.",
                            GitCredentialId = 1,
                            Language = 1,
                            LogoId = 3,
                            Name = "non",
                            ProjectLink = "http://alivia.net",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 18,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 5,
                            CountOfSaveBuilds = 7,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5403),
                            Description = "Molestias dolor at neque molestiae.",
                            GitCredentialId = 11,
                            Language = 1,
                            LogoId = 5,
                            Name = "omnis",
                            ProjectLink = "https://torrey.info",
                            ProjectType = 1
                        },
                        new
                        {
                            Id = 19,
                            AccessModifier = 1,
                            AuthorId = 1,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5480),
                            Description = "Sit ex culpa laudantium quos.",
                            GitCredentialId = 5,
                            Language = 1,
                            LogoId = 4,
                            Name = "ut",
                            ProjectLink = "http://marlene.com",
                            ProjectType = 0
                        },
                        new
                        {
                            Id = 20,
                            AccessModifier = 0,
                            AuthorId = 3,
                            CompilerType = 0,
                            CountOfBuildAttempts = 8,
                            CountOfSaveBuilds = 8,
                            CreatedAt = new DateTime(2019, 8, 9, 14, 52, 32, 703, DateTimeKind.Local).AddTicks(5557),
                            Description = "Ut iure minus voluptates quo.",
                            GitCredentialId = 17,
                            Language = 0,
                            LogoId = 6,
                            Name = "consectetur",
                            ProjectLink = "https://neva.info",
                            ProjectType = 2
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId");

                    b.Property<int>("UserId");

                    b.Property<int>("UserAccess");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectId = 13,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 10,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 18,
                            UserId = 3,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 16,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = 1,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 9,
                            UserId = 3,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 17,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 14,
                            UserId = 3,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 3,
                            UserId = 3,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 17,
                            UserId = 1,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 10,
                            UserId = 2,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 18,
                            UserId = 1,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 5,
                            UserId = 2,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 6,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = 2,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 15,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 20,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 12,
                            UserId = 1,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 11,
                            UserId = 2,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 19,
                            UserId = 1,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 15,
                            UserId = 2,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 8,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 4,
                            UserId = 2,
                            UserAccess = 1
                        },
                        new
                        {
                            ProjectId = 9,
                            UserId = 2,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 20,
                            UserId = 1,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 12,
                            UserId = 3,
                            UserAccess = 0
                        },
                        new
                        {
                            ProjectId = 7,
                            UserId = 3,
                            UserAccess = 3
                        },
                        new
                        {
                            ProjectId = 7,
                            UserId = 2,
                            UserAccess = 2
                        },
                        new
                        {
                            ProjectId = 7,
                            UserId = 1,
                            UserAccess = 3
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IDE.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("GitHubUrl");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("LastName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<DateTime>("RegisteredAt");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 11,
                            Birthday = new DateTime(2005, 7, 27, 11, 17, 51, 342, DateTimeKind.Local).AddTicks(6360),
                            Email = "Alexie.Pfannerstill@hotmail.com",
                            FirstName = "Eli",
                            GitHubUrl = "http://hassan.net",
                            LastActive = new DateTime(2019, 8, 9, 14, 52, 32, 474, DateTimeKind.Local).AddTicks(4318),
                            LastName = "Bruen",
                            PasswordHash = "9uTPd7mj/z+SYU7XaaKToshH97UvpSBu2x73XIVl2bE=",
                            PasswordSalt = "AwnD5Ti7RB6EnPN7oqPgWWFfg1XLUQF8A8+1FLTwVWY=",
                            RegisteredAt = new DateTime(2019, 8, 9, 14, 52, 32, 474, DateTimeKind.Local).AddTicks(3527)
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 5,
                            Birthday = new DateTime(2016, 4, 2, 1, 25, 12, 680, DateTimeKind.Local).AddTicks(1011),
                            Email = "Keely.Orn56@gmail.com",
                            FirstName = "Stuart",
                            GitHubUrl = "https://aileen.net",
                            LastActive = new DateTime(2019, 8, 9, 14, 52, 32, 536, DateTimeKind.Local).AddTicks(4095),
                            LastName = "Hegmann",
                            PasswordHash = "I9gAvQllWWXBDFe5tL/ODCI7dwybxgmKNVOblYwcRXg=",
                            PasswordSalt = "NPruXrCT44kyJuRoLs2vZw7G/jGRjj1URHrWDbogTZ4=",
                            RegisteredAt = new DateTime(2019, 8, 9, 14, 52, 32, 536, DateTimeKind.Local).AddTicks(4085)
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 1,
                            Birthday = new DateTime(2005, 8, 9, 14, 52, 32, 549, DateTimeKind.Local).AddTicks(1672),
                            Email = "test@gmail.com",
                            FirstName = "testUser",
                            LastActive = new DateTime(2019, 8, 9, 14, 52, 32, 549, DateTimeKind.Local).AddTicks(1693),
                            LastName = "testUser",
                            PasswordHash = "nDTD8rc6+J+jdWxkvear98SjScUULQZoVgiIjKWRImY=",
                            PasswordSalt = "cCYNcAyoUUvEGeYaaDXHcCF6o/JjfUIBUjeVa6zrnWw=",
                            RegisteredAt = new DateTime(2019, 8, 9, 14, 52, 32, 549, DateTimeKind.Local).AddTicks(1698)
                        });
                });

            modelBuilder.Entity("IDE.DAL.Entities.Build", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Project", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany("Builds")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.Project", b =>
                {
                    b.HasOne("IDE.DAL.Entities.User", "Author")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.GitCredential", "GitCredential")
                        .WithMany()
                        .HasForeignKey("GitCredentialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.Image", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.ProjectMember", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IDE.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("IDE.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IDE.DAL.Entities.User", b =>
                {
                    b.HasOne("IDE.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
